### PR TITLE
Update phpcs.

### PR DESCRIPTION
**Pull request by Camwyn**
Back to using Squiz but update the versions of:

- PHP to ^7.4
- PHPCS: ^3.8.0
- WPCS: ^3.0.0

### CODE REVIEW

**Review by bordoni — APPROVED** [review]

**Comment by sc0ttkclark** [comment]
This is no longer necessary, they were able to point the original to the new repository. Keep it as-is for the proper package to be referenced there.

**Comment by sc0ttkclark** [comment]
See https://github.com/squizlabs/PHP_CodeSniffer/issues/3932#issuecomment-1845632122

**Comment by borkweb** [comment]
That being said, there's no harm in the shifting to the authoritative source - it looks like both the squizlabs and the phpcsstandards packagist are being kept in sync.

**Review by borkweb — APPROVED** [review]

**Comment by sc0ttkclark** [comment]
Don't merge this, release notes say the phpcsstandards package will be shut down at some point.

https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0

This was a challenge because squiz will not transfer the repo but in the end they did allow remapping the packagist package.

**Comment by Camwyn** [comment]
> Don't merge this, release notes say the phpcsstandards package will be shut down at some point.
> 
> https://github.com/PHPCSStandards/PHP_CodeSniffer/releases/tag/3.8.0
> 
> This was a challenge because squiz will not transfer the repo but in the end they did allow remapping the packagist package.

What I see is:
>For Composer users, nothing changes.
In contrast to earlier information, the squizlabs/php_codesniffer package now points to the new repository and everything will continue to work as before.

So the change isn't needed, but I don't see the note that says the new package will get shut down.

That being said, I can adjust for that.

**Comment by Camwyn** [comment]
@sc0ttkclark how's that? (I can't add you as a reviewer)

**Review by sc0ttkclark — APPROVED** [review]
Looks good to me

**Comment by sc0ttkclark** [comment]
Sorry, that part was info I had chatted with her about her plans for the phpcsstandards packagist package. Her plan is to shut it down, she wants everyone to use the squiz package to avoid issues maintaining and supporting long term.

**Comment by Camwyn** [comment]
> Sorry, that part was info I had chatted with her about her plans for the phpcsstandards packagist package. Her plan is to shut it down, she wants everyone to use the squiz package to avoid issues maintaining and supporting long term.

I appreciate the heads-up. If that is the plan, she should probably make a public announcement (if she hasn't already)

**Review by ggwicz — APPROVED** [review]
🚀 

> Sorry, that part was info I had chatted with her about her plans for the phpcsstandards packagist package. Her plan is to shut it down, she wants everyone to use the squiz package to avoid issues maintaining and supporting long term.

**awesome**

**Review by borkweb — APPROVED** [review]

**Comment by borkweb** [comment]
Merging this now!

**Pull request merged**
