### PR TITLE
Change our classname standard.

### PR DESCRIPTION
**Pull request by Camwyn**
Using the power of regex, we enforce capitalize snake case for our class names.

[Regex](https://regexr.com/7p0vp)

Honestly not sure the best way to test this?

### CODE REVIEW

**Comment by bordoni** [comment]
I've made a small change to the Regular expression. That prevents a couple of other things.
https://regexr.com/7p0q2

**Comment by borkweb** [comment]
I expanded to prevent mixed underscores and removed the extraneous `]*` that was in there.

https://regexr.com/7p0vp

**Review by borkweb — CHANGES_REQUESTED** [review]
Adopt my regex and this is looking good!

**Comment by Camwyn** [comment]
Here are the strings I used for testing:

**Accept:**

- Legit
- Proper_Snake_Case
- Big_ID
- HTML_Pancake
- Mixed_SNakecase
- UPPERCASE

**Reject:**

- little_snake_case
- Old__Snake__BadCase
- Mixed_SnakeCase
- Too___Many
- IncorretName_New
- CamelCase
- Mix_ASDF__Adf
- Old__Mixed_Case
- Tribe__Tabbed_View__Tab
- Old__Snake__Case

**Comment by Camwyn** [comment]
And the newest iteration of the regex: https://regexr.com/7p2sh

**Review by borkweb — APPROVED** [review]

**Pull request merged**
